spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

logging:
  level:
    com.swipeprep: DEBUG
    com.swipeprep.appbackend.repository: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      # Token validity in milliseconds (24 hours)
      expiration: 8640000000

server:
  address: 0.0.0.0
  port: 8080