spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.swipeprep: DEBUG

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      # Token validity in milliseconds (24 hours)
      expiration: 86400000